#!/usr/bin/env python3
"""Generate data/kernel/se_deltat_parity.csv — the ΔT parity grid.

Black-box samples of Swiss Ephemeris 2.10.03 ΔT (KERNEL.md §5, §11: the SE
*outputs* are a sanctioned clean-room source; no SE code was consulted).
Two production flavours:

  dt_swieph : swe_deltat_ex(jd, SEFLG_SWIEPH)  — tidal acceleration of DE431
              (ndot = -25.80 "/cy^2). Consumed by engine.delta_t,
              Julian-calendar moment resolution, progressed moments.
  dt_jpleph : swe_deltat_ex(jd, SEFLG_JPLEPH). This is the flavour
              swe_utc_to_jd applies internally when deriving JD_UT1
              (measured: |(tt-ut1) - dt_jpleph| <= 1.5e-5 s, 1820..2017).
              The flavours coincide after 1955 (tidal adjustment applies
              to epochs before 1955 only — SE manual, "ΔT" chapter).

Grid: 10-day nodes 1799..1955 (the SMH-spline era carries the most local
curvature — up to ~8e-6 s/day^2 around 1850, measured), monthly nodes
1955-01..2035-01 (includes every Jan-1 table vertex of SE's modern era),
quarterly 2035-04..2402-01.  Linear interpolation between nodes then errs
<= f''*h^2/8 ~= 1e-4 s everywhere — two orders under the 0.01 s acceptance
bound (verified against off-node samples in tests/kernel).

Run on a machine with the vendored pyswisseph importable (macOS: vendor/lib).
Deterministic: same SE version -> byte-identical output.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "vendor" / "lib"))
import swisseph as swe  # noqa: E402

swe.set_ephe_path(str(ROOT / "data" / "ephe"))

OUT = ROOT / "data" / "kernel" / "se_deltat_parity.csv"


def main() -> None:
    jds = []
    j1955 = swe.julday(1955, 1, 1, 0.0, swe.GREG_CAL)
    j = swe.julday(1799, 1, 1, 0.0, swe.GREG_CAL)
    while j < j1955:                      # 10-day nodes, high-curvature era
        jds.append(j)
        j += 10.0
    for y in range(1799, 1956):
        # SE's pre-1955 ΔT is linear within each year with a ~1 ms jump at
        # every Jan-1 (measured sawtooth). Bracket each boundary: one node
        # 0.01 d before the jump, one at it.
        jy = swe.julday(y, 1, 1, 0.0, swe.GREG_CAL)
        jds.extend((jy - 0.01, jy))
    for y in range(1955, 2403):
        months = range(1, 13) if y < 2035 else (1, 4, 7, 10)
        for m in months:
            jds.append(swe.julday(y, m, 1, 0.0, swe.GREG_CAL))
            if y == 2402:
                break
    jds = sorted(set(jds))
    with open(OUT, "w") as f:
        f.write("# SE 2.10.03 delta-T parity grid; generated by "
                "tools/gen_deltat_parity.py (see header there)\n")
        f.write("# columns: jd_ut, dt_swieph_sec, dt_jpleph_sec\n")
        for j in jds:
            a = swe.deltat_ex(j, swe.FLG_SWIEPH) * 86400.0
            b = swe.deltat_ex(j, swe.FLG_JPLEPH) * 86400.0
            f.write(f"{j:.2f},{a:.9f},{b:.9f}\n")
    print(f"wrote {OUT} ({len(jds)} nodes)")


if __name__ == "__main__":
    main()
